name: Trivy Docker Container in Actions

on:
  workflow_dispatch:

jobs:
  run_semgrep:
    runs-on: ubuntu-latest
    container: 
      image: zerosource/dojo-s3import-trivy
      env:
        LAMBDA_URL: ${{ secrets.LAMBDA_URL }}
        APP_ID: ${{ secrets.APP_ID_TRIVY }}
        
    steps:
    - uses: actions/checkout@v2

    - name: Run Commands inside Docker Container
      run: |
        trivy fs --format sarif -o $RUNNER_TEMP/output.sarif $GITHUB_WORKSPACE
        upload-results-s3.sh $RUNNER_TEMP/output.sarif
