name: Gitleaks Docker Container in Actions

on:
  workflow_dispatch:

jobs:
  run_semgrep:
    runs-on: ubuntu-latest
    container: 
      image: zerosource/dojo-s3import-gitleaks
      env:
        LAMBDA_URL: ${{ secrets.LAMBDA_URL }}
        APP_ID: ${{ secrets.APP_ID_GITLEAKS }}
        
    steps:
    - uses: actions/checkout@v2

    - name: Run Commands inside Docker Container
      run: |
        gitleaks detect -f sarif -r $RUNNER_TEMP/output.sarif -s $GITHUB_WORKSPACE
        upload-results-s3.sh $RUNNER_TEMP/output.sarif
